# -*- coding: utf-8 -*-
"""Assignment1_CS_202151011.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nyE1tIG9GapKRCh95CQkhND5-KeVCAQl

# DAV ASSIGNMENT1
Dipean Dasgupta
202151188

**Importing libraries**
"""

import pandas as pd
import json

from google.colab import drive
drive.mount('/content/drive')



Data=pd.read_csv("/content/drive/MyDrive/CS312_DA/district_level_service_msme.csv")

filepath="/content/drive/MyDrive/CS312_DA/district_level_manufacturing_msme.json"
f=open(filepath)
Data2= json.load(f)

Data.head()

"""**T1**"""

df1=pd.DataFrame(Data)
df1

df2=pd.DataFrame(Data2["data"])
df2

colms=[dic["label"] for dic in Data2["fields"]]
print(colms)
df3=pd.DataFrame(Data2["data"],columns=colms)
df3

"T2"

df3['SMALL']=df3['SMALL'].astype(int)
Small_total= df3['SMALL'].sum()
print("Total MSME:", Small_total)

"T3"

df3['MICRO']=df3['MICRO'].astype(int)
df3['MEDIUM']=df3['MEDIUM'].astype(int)
df_state_totals = df3.groupby('STATE_NAME',as_index=False).agg({
    'MICRO': 'sum',
    'SMALL': 'sum',
    'MEDIUM': 'sum'
})
print(df_state_totals.to_string(index=False))
df_state_totals.to_csv('state_wise_total.csv',index=False)

df3['Lg_Dist_Code'] = df3['Lg_Dist_Code'].astype(int)
df3['Last_Updated'] = pd.to_datetime(df3['Last_Updated'])
df1['Last_Updated'] = pd.to_datetime(df1['Last_Updated'])

"T4"

dfm = pd.merge(df1, df3, on=['STATE_NAME', 'DISTRICT_NAME', 'Lg_Dist_Code', 'Last_Updated'])
dfm

"T5"

df_pivot = dfm[['STATE_NAME', 'MICRO_x', 'MICRO_y', 'SMALL_x', 'SMALL_y', 'MEDIUM_x', 'MEDIUM_y']]
pivot_table = df_pivot.pivot_table(index='STATE_NAME', aggfunc='sum')

pivot_table_reset = pivot_table.reset_index()

print(pivot_table_reset.to_string(index=False))